version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: aggregation-api

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    volumes:
      - ./config.yaml:/app/config.yaml
      - ./validation_schema.json:/app/validation_schema.json

    restart: unless-stopped

  postgres:
    image: postgres:16

    container_name: aggregation-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: aggregation_dashboard

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: aggregation-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

volumes:
  postgres_data: